# Deep Learning in Medicine
### BMSC-GA 4493, BMIN-GA 3007 
### Lab 1: PyTorch Tutorial and Loss Functions


### Goal of this lab: 
    - Understand Pytorch Tensor, and AutoGrad (Variable is deprecated in the new version of pytorch). 
    - Understand Loss Functions

### What is PyTorch?
It's a Python based scientific computing package targeted as:
* A replacement for numpy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed

### Tensor
It is similar to Numpy Ndarray
<a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html 


In [1]:
from __future__ import print_function
import torch

#### Check Version of the Pytorch

In [2]:
print(torch.__version__)

1.7.0


#### Tensor Initialization

In [3]:
x = torch.Tensor(6, 2)  # construct a 6x2 matrix, uninitialized

In [4]:
x, x.size()

(tensor([[1.1632e+33, 5.6003e-02],
         [7.0374e+22, 5.7453e-44],
         [0.0000e+00, 2.0000e+00],
         [0.0000e+00, 2.0000e+00],
         [1.4569e-19, 6.4069e+02],
         [4.3066e+21, 1.1824e+22]]),
 torch.Size([6, 2]))

In [5]:
y = torch.rand(6, 2)  # construct a randomly initialized matrix


In [6]:
y, y.size()

(tensor([[0.5532, 0.0095],
         [0.9398, 0.2468],
         [0.7564, 0.0577],
         [0.4510, 0.7600],
         [0.9945, 0.6033],
         [0.8722, 0.0122]]),
 torch.Size([6, 2]))

In [7]:
z = torch.ones(7) # construct a matrix of ones

In [8]:
z, z.size()

(tensor([1., 1., 1., 1., 1., 1., 1.]), torch.Size([7]))

#### Operation Example: Addtion
Related reading and reference:
    
* PyTorch documentation:
<a href="https://pytorch.org/docs/stable/nn.html"> https://pytorch.org/docs/stable/nn.html </a>

In [9]:
# addition: syntax 1
x + y

tensor([[1.1632e+33, 6.5509e-02],
        [7.0374e+22, 2.4680e-01],
        [7.5641e-01, 2.0577e+00],
        [4.5100e-01, 2.7600e+00],
        [9.9446e-01, 6.4129e+02],
        [4.3066e+21, 1.1824e+22]])

In [10]:
# addition: syntax 2
torch.add(x, y)

tensor([[1.1632e+33, 6.5509e-02],
        [7.0374e+22, 2.4680e-01],
        [7.5641e-01, 2.0577e+00],
        [4.5100e-01, 2.7600e+00],
        [9.9446e-01, 6.4129e+02],
        [4.3066e+21, 1.1824e+22]])

In [11]:
# addition: giving an output tensor
result = torch.Tensor(6, 2)
torch.add(x, y, out=result)

tensor([[1.1632e+33, 6.5509e-02],
        [7.0374e+22, 2.4680e-01],
        [7.5641e-01, 2.0577e+00],
        [4.5100e-01, 2.7600e+00],
        [9.9446e-01, 6.4129e+02],
        [4.3066e+21, 1.1824e+22]])

In [12]:
# addition: in-place
y.add_(x) # adds x to y

tensor([[1.1632e+33, 6.5509e-02],
        [7.0374e+22, 2.4680e-01],
        [7.5641e-01, 2.0577e+00],
        [4.5100e-01, 2.7600e+00],
        [9.9446e-01, 6.4129e+02],
        [4.3066e+21, 1.1824e+22]])

#### Numpy Bridge:
The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

##### Convert Torch Tensor to Numpy

In [13]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [14]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
a.add_(1) # Remember this is an inplace addition
print(a)
print(b) # see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##### Converting Numpy Array to Torch Tensor

In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


####  Used of CUDA

In [17]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### Autograd: automatic differentiation
* The autograd package provides automatic differentiation for all operations on Tensors.It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

### Tensor
* torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it.
* When you finish your computation you can call .backward() and have all the gradients computed automatically.
* The gradient for this tensor will be accumulated into .grad attribute.
* To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

### Function
* Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation.
* Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

Related Reading and Reference:
<a href="https://pytorch.org/docs/stable/autograd.html"> https://pytorch.org/docs/stable/autograd.html </a>

In [18]:
import torch

In [19]:
x = torch.ones((2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [21]:
print(y.grad_fn)

In [22]:
z = y * y * 2
out = z.mean()
print(z, out)

tensor([[18., 18.],
        [18., 18.]], grad_fn=<MulBackward0>) tensor(18., grad_fn=<MeanBackward0>)


In [23]:
# What's the gradient of X before backward() is performed?
print(x.grad)

None


In [24]:
# What's the correct gradient of X?
out.backward()
print(x.grad)

tensor([[3., 3.],
        [3., 3.]])


In [25]:
print(y.grad)

None


/Users/rh2740/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


### Loss Functions

 Related Reference: 
<a href="http://pytorch.org/docs/master/nn.html#loss-functions">http://pytorch.org/docs/master/nn.html#loss-functions </a>

#### Mean Squared Error

In [26]:
import torch.nn as nn
input = torch.randn((4, 5), requires_grad=True)
target = torch.randn(4, 5)

In [27]:
print(input)
print(target)

tensor([[ 0.0270,  0.0467, -0.5995, -1.5226, -0.7597],
        [ 0.8794,  0.3176,  0.1796, -0.8550,  0.1265],
        [-0.6853, -1.2270,  0.1474,  2.9559, -0.0308],
        [ 0.0666, -0.6587, -0.6442,  1.0076, -2.2955]], requires_grad=True)
tensor([[ 0.2562, -0.5330, -0.3883, -1.5687,  0.1057],
        [ 0.1726, -0.1616,  1.2776,  0.0167,  1.6215],
        [-1.2269, -1.0384,  0.7296, -0.0178, -0.0030],
        [ 0.5540,  0.3658, -0.6702,  1.4077, -0.7608]])


In [28]:
loss = nn.MSELoss()
output = loss(input, target)
output.backward()

In [29]:
output, input

(tensor(0.9715, grad_fn=<MseLossBackward>),
 tensor([[ 0.0270,  0.0467, -0.5995, -1.5226, -0.7597],
         [ 0.8794,  0.3176,  0.1796, -0.8550,  0.1265],
         [-0.6853, -1.2270,  0.1474,  2.9559, -0.0308],
         [ 0.0666, -0.6587, -0.6442,  1.0076, -2.2955]], requires_grad=True))

### Reference:
* Deep Learning with PyTorch: A 60 Minute Blitz:
    <a href="http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html">http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
    
    
* PyTorch documentation:
<a href="https://pytorch.org/docs/stable/nn.html"> https://pytorch.org/docs/stable/nn.html </a>